### ISSUE TITLE
Adding a message to Git tag

### ISSUE THREAD

**Issue by sander1095** [ReneSorensen/VSTSTools#12]
Hello.

I think being able to add a message to GIT TAG would be nice!

What do you think?

**Comment by VisualBean** [comment]
What sort of message?

**Comment by sander1095** [comment]
A git tag has the option to add a message (https://git-scm.com/book/en/v2/Git-Basics-Tagging) using the `-m` parameter. It would be nice to be able to add a message to a git tag using this plug-in.

**Comment by VisualBean** [comment]
Ahh good show! - Ill look into it :)

**Comment by VisualBean** [comment]
Will implement as part of #13
