### ISSUE TITLE
Cross Platform Support [Comment]

### ISSUE THREAD

**Issue by bernienowel** [ReneSorensen/VSTSTools#20]
Now that there is both a Powershell and nodeJs version of this extension it could make sense to only use the nodeJs one.  I haven't actually tested if it will ever use the Powershell version but if they are both active it will make ongoing support more difficult.

https://github.com/ReneSorensen/VSTSTools/blob/2bebe401f7b9b5c3a5811fc881e7b8072cbd0191/GitTag/GitTag/task.json#L84

**Comment by VisualBean** [comment]
I agree, support will get increasingly more complex with both versions. . I will test out the new version and see if it uses ps1.

**Comment by VisualBean** [comment]
Ps1 is never called now -
Ill deprecate the powershell one.
