### ISSUE TITLE
GIT Tag with the new YAML build definitions

### ISSUE THREAD

**Issue by mccw** [ReneSorensen/VSTSTools#22]
I'm having issues with the Git Tag build step and after corresponding with Microsoft they suggest the following change in the tagging.ps1 script:

I've made the  change locally and it does work.

task code not working today:

if (!($env:SYSTEM_ACCESSTOKEN )) {
    throw ("OAuth token not found. Make sure to have 'Allow Scripts to Access OAuth Token' enabled in the build definition.
			Also, give 'Project Collection Build Service' 'Contribute' and 'Create Tag' permissions - Cog -> Version Control -> {Select Repository/ies}")
}
Task code should work:

if (!(Get-VstsTaskVariable -Name "System.AccessToken")) {
    throw ("OAuth token not found. Make sure to have 'Allow Scripts to Access OAuth Token' enabled in the build definition.
			Also, give 'Project Collection Build Service' 'Contribute' and 'Create Tag' permi

**Comment by VisualBean** [comment]
Awesome. Thanks for the PR.

I have split the old ps1. one into a separate extension and the main extensions is now the nodejs one.
You can find it here https://marketplace.visualstudio.com/items?itemName=visualbean.GitTag-WindowsHost
:)

Thank you for your contribution :)

**Comment by mccw** [comment]
I just tested the new step in Azure DevOps and it works great!

Have a great weekend!

Scott
