### ISSUE TITLE
Modal Dialog Box Suppression using Git Tag

### ISSUE THREAD

**Issue by jonathandbyrd** [ReneSorensen/VSTSTools#25]
Env: Azure Devops with Azure Git Repos
Task: Trying to tag git branch with Git Tag (and Git Tag (WindowsHost)) during a release pipeline
Config: followed all recommended instructions to allow Oauth and give appropriate permissions to the service
Error: fatal: InvalidOperationException encountered.
   Showing a modal dialog box or form when the application is not running in UserInteractive mode is not a valid operation. Specify the ServiceNotification or DefaultDesktopOnly style to display a notification from a service application.

this dialog is the VSTS login screen. just wondering how to get around it or what's the solution, maybe use the SSH authentication option?

**Comment by ReneSorensen** [comment]
Hi

As you said you make sure to have 'Allow Scripts to Access OAuth Token'
enabled in the build or release definition and also make sure that you have
'ALLOW' in 'Create tag definition' in Security permissions.
Hope this helps.
Regards
René

Den tor. 10. jan. 2019 kl. 17.22 skrev Jonathan D Byrd <
notifications@github.com>:

**Comment by VisualBean** [comment]
Closing as this is now 2 months old :)
