### ISSUE TITLE
Tag message not applied to resulting tag

### ISSUE THREAD

**Issue by nsturdivant** [ReneSorensen/VSTSTools#26]
I'm using Git Tag version [1.1.20](https://marketplace.visualstudio.com/items?itemName=ATP.ATP-GitTag) in an Azure DevOps build pipeline. Everything is working as expected save for the application of the tag message. I'm using pipeline variables in several fields and it seems to work fine for every field except the tag message. Here's my configuration:

![image](https://user-images.githubusercontent.com/3599714/51041823-c1a40c00-1588-11e9-9053-fe0df8b19e46.png)

The tag is successfully created, but the tag message is always `${tagMessage}`.

Looking at the recent commits, [this commit](https://github.com/ReneSorensen/VSTSTools/commit/03b04efd47ed042907522dfcea1850fe53c983a8#diff-8c6a6008ff82bc31236802a0cb1570e5) seems to include a fix for this. And [this commit](https://github.com/ReneSorensen/VSTSTools/commit/be7256e54a1fe1425d16152e34fb0d31eee5ea58)  bumps the Git Tag task version to `5.1.1`.

Does version 1.1.20 include this fix? Has the latest version of Git Tag simply not been published to the Azure DevOps Marketplace yet? Should tag messages be working with the version of Git Tag I'm using 😃?

**Comment by ReneSorensen** [comment]
Hi
Sorry for that, I have released a new version1.1.21
Regards
René

Den fre. 11. jan. 2019 kl. 16.13 skrev Nick Sturdivant <
notifications@github.com>:

**Comment by nsturdivant** [comment]
Cheers, thanks @ReneSorensen! I just reran my build and had the same issue. I'll try again tomorrow with the debug variable set to true to get more information and to verify versions. I don't need to re-add the task from the marketplace or anything, do I?

**Comment by VisualBean** [comment]
No you dont need to readd it, it should self upgrade so to speak :)

Mvh Alex

________________________________

**Comment by nsturdivant** [comment]
Can confirm; my tag messages are now appearing correctly in the resulting tags. I'm closing this issue. I appreciate the quick replies, @ReneSorensen and @VisualBean. 👍
