### ISSUE TITLE
Unable to push tag

### ISSUE THREAD

**Issue by rioka** [ReneSorensen/VSTSTools#28]
I'm using Git Tag in an Azure DevOps build pipeline, but I always get a error when the tag is pushed to the repository.

Here is the output
```
##[section]Starting: GitTag 
==============================================================================
Task         : Git Tag
Description  : A simple task that tags a branch
Version      : 5.1.3
Author       : ATP P&I IT
Help         : tags the current branch with a specified tag. ### Prerequisites * Repository must be VSTS Git. * Allow scripts to access Oauth must be **Enabled** * Project Collection Build Service must have **Contribute** & **Create Tag** set to **Allow** or **Inherit Allow** for that particular repository
==============================================================================
Setting working directory to 'd:\a\1\s'.
##[command]git config user.email "noreply@example.com"
##[command]git config user.name "VSTS"
##[command]git tag  -a "v0.1.0" -m "Version 0.1.0"
Push tag to origin
##[command]git push origin v0.1.0
##[error]Command failed: git push origin v0.1.0 
remote: 001f# service=git-receive-pack
remote: 0000000000aaTF401027: You need the Git 'GenericContribute' permission to perform this action. Details: identity 'Build\c98***********', scope 'repository'.
remote: TF401027: You need the Git 'GenericContribute' permission to perform this action. Details: identity 'Build\c98********', scope 'repository'.
fatal: unable to access 'https://****.visualstudio.com/***/_git/***/': The requested URL returned error: 403

##[error]Git Repo Tagger Failed.
##[section]Finishing: GitTag 
```
Looking at similar issues, I managed to set all required permissions.
![image](https://user-images.githubusercontent.com/383147/58455637-1dc39300-811a-11e9-8432-4c4d62dca8af.png)

Tried using both plain yaml pipeline and a the _classic_ one. In both cases, OAuth is enabled.

Any suggestions?
TIA

**Comment by rioka** [comment]
Solved...
Don't know why, but that project has no "Project Collection Build Service" account under "Users": once I added that, and granted permissions, everything worked

**Comment by Yogoort** [comment]
I faced with pretty similar issue.
Checked security tab for my repo and there was "**Project Collection Build Service**" User with necessary creds.
And only after comparing the identity ids (**guid**) from build logs, I got the point, that it was different user.
So you need just to past the **guid** of your build agent to search input and set **Grant** permissions for specified user.

![image](https://user-images.githubusercontent.com/39881107/163450124-3ef685a4-da3d-4135-9fca-869bdf7c2755.png)
