### ISSUE TITLE
[Waiting] Files from other PRs are getting pulled in

### ISSUE THREAD

**Issue by aramakris21** [ReneSorensen/VSTSTools#30]
I am using the GitCopyDiff task in my build pipeline and have lately notices an issue where occasionally files from a different PR are showing up in the PR branch that being processed by the build pipeline. What could be causing this and how do I fix?

**Comment by VisualBean** [comment]
This sounds unlikely. Do you have some repro steps?

**Comment by VisualBean** [comment]
Could it be specifically delete files, or something similar?
do you have any repro steps?

**Comment by ReneSorensen** [comment]
Hi Sorry the late answer.
The Git Copy diff task is finding the difference between two git-commits. It use 'git diff --name-status $old_commit_hash $new_commit_hash' to find difference between the commits. 
You can see definition here: The Git Copy diff task is finding the difference between two git-commits. It use 'git diff --name-status $old_commit_hash $new_commit_hash' to find difference between the commits. 
I think the commits are not the one you have expected, try execute the git command to see what the result is.
