### ISSUE TITLE
Passing database login credentials to task

### ISSUE THREAD

**Issue by parthdesai9369** [ReneSorensen/VSTSTools#39]
How do I pass database login credentials to this task? Whenever I run this task it says not connected. There are no fields to provide input for login id, password and database name.

**Comment by ReneSorensen** [comment]
Hi

The SQLPuls-executer does not do the login (connection).
We create the connection (login) in the SQL scripts that are being executed.
You can added the following in the beginning of your sql-files (
https://docs.oracle.com/cd/B14117_01/server.101/b12170/qstart.htm)

*connect ***@***.***_identifier*



Here is an example of a SQL-file, we are using Kerberos therefore are we
not using user/password:

WHENEVER OSERROR EXIT 9;
WHENEVER SQLERROR EXIT SQL.SQLCODE;
set echo off
set define off
set errorlogging on
--disconnect
connect ***@***.***_identifier
set echo on

select sysdate from dual;




Den fre. 25. jun. 2021 kl. 10.55 skrev parthdesai9369 <
***@***.***>:
